### ISSUE TITLE
libsg_nvim not found

### ISSUE THREAD

**Issue by thuan1412** [tjdevries/sg.nvim#4]
The plugin is importing `libsg_nvim`, which is linked to `/home/tjdevries/plugins/sg.nvim/target/debug/libsg_nvim.so`, while `target` is included in the `.gitingore` file.

**Comment by thuan1412** [comment]
For people who cannot wait for the fix, you can install the latest working version of `sg` at this commit.
```lua
  use {
    'tjdevries/sg.nvim',
    commit = '76354e9f0b6de39134ec9efcd022f079ae0ce02b'
  }

```

**Comment by tjdevries** [comment]
Sorry, the old build instructions were wrong and I haven't been working on this for quite awhile.

New instructions might actually work if you wanted to try this out. I'll be playing with this project a bit more again over the next few months

**Comment by tjdevries** [comment]
Hey @thuan1412 I finally resurrected this project at work with new instructions about how to use it, if you want to give it a try again, let me know :) I'd be happy to try and solve any new build problems you have.

**Comment by tjdevries** [comment]
I'm going to close this issue cause I think I've solved all of the currently existing issues -- if you encounter something new, please open a new issue :)
