### ISSUE TITLE
sg-lsp quits with error code 1

### ISSUE THREAD

**Issue by jcdickinson** [tjdevries/sg.nvim#7]
I get this when I attempt to goto definition (NixOS, nvim 0.8.2) on `sg://github.com/tjdevries/vim9jit/-/blob/src/main.rs` line 97 (`gen_directory`):

```
[ERROR][2023-01-18 12:10:40] .../vim/lsp/rpc.lua:733	"rpc"	"/home/jono/.local/share/nvim/site/pack/packer/start/sg.nvim/target/debug/sg-lsp"	"stderr"	"Error: No corresponding code intelligence\n"
```

The LSP probably shouldn't crash.

**Comment by tjdevries** [comment]
:+1: good call, i'll work on that today

**Comment by tjdevries** [comment]
Ok, just pushed up some changes -- I tested locally and it seems to fix the problem for me . Let me know if latest build works for you :)

**Comment by jcdickinson** [comment]
It works! :shipit:

**Comment by tjdevries** [comment]
Awesome :)
